version: '3.8'

services:
  php:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./public:/var/www/html
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "MySuperSecurePassword1!"
    ports:
      - "1433:1433"
